ARG VARIANT="bullseye"
FROM buildpack-deps:${VARIANT}
LABEL maintainer="SunshineCloudTech"
ENV container="docker"
ENV pip_packages="ansible"
USER root 
# Update package list and install basic packages
RUN apt-get update && apt-get upgrade -y && apt-get clean
# Enable systemd.
RUN apt-get update && \
    apt-get install -y systemd systemd-sysv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

# Install pip and other requirements.
RUN apt-get update \
  && apt-get install -y \
    python3-pip \
    sudo xterm \
    curl wget \
    ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
# Setup System User and Permissions  
RUN useradd -m "Administrator" -s /bin/bash && \
    echo "Administrator:123456789" | chpasswd && \
    echo "root:123456789" | chpasswd && \
    usermod -d /home/Administrator/ Administrator && \
    usermod -aG sudo Administrator && \
    useradd -m "matrix0523" -s /bin/bash && \
    echo "matrix0523:123456789" | chpasswd && \
    usermod -d /home/matrix0523/ matrix0523 && \
    usermod -aG sudo matrix0523 && \
    echo 'matrix0523 ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/matrix0523 && \
    # Create ollama user
    useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama && \
    usermod -a -G ollama root && \
    usermod -a -G ollama Administrator && \
    usermod -a -G ollama matrix0523 && \
    # Setup Ollama directories and permissions
    mkdir -p /var/lib/ollama/models && \
    chown -R ollama:ollama /var/lib/ollama && \
    chmod -R 755 /var/lib/ollama
# Install Ansible via Pip.
RUN pip3 install $pip_packages
# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers
# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh
# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
